package com.epicodus.marvelsquare.ui;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.ListView;
import android.widget.TextView;
import android.widget.Toast;

import com.epicodus.marvelsquare.R;

public class AllHeroesActivity extends AppCompatActivity {
    private ListView mAllHeroesListView;
    private String[] allHeroListVal;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_all_heroes);

        mAllHeroesListView = (ListView) findViewById(R.id.allHeroesListView);
        allHeroListVal = getResources().getStringArray(R.array.all_heroes);

        ArrayAdapter adapter = new ArrayAdapter(this, android.R.layout.simple_list_item_1, allHeroListVal);
        mAllHeroesListView.setAdapter(adapter);

        mAllHeroesListView.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
//            This toast to be Replaced by the individual character screens as generated by the Marvel API
            public void onItemClick(AdapterView<?> adapterView, View view, int i, long l) {
                String hero = ((TextView)view).getText().toString();
                Toast.makeText(AllHeroesActivity.this, hero, Toast.LENGTH_SHORT).show();
            }
        });


    }
}
